---
name: "deploy"
version: "0.6.8"
usage: "Integrate vault with Helm"
description: |-
  This plugin provides vault secrets to Helm.
ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/deploy.py"



